// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: beeplug.proto

package beeplug

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	// Basic Types
	DataType_Int8     DataType = 0
	DataType_Int16    DataType = 1
	DataType_Int32    DataType = 2
	DataType_Int64    DataType = 3
	DataType_UInt8    DataType = 4
	DataType_UInt16   DataType = 5
	DataType_UInt32   DataType = 6
	DataType_UInt64   DataType = 7
	DataType_Float    DataType = 8
	DataType_Double   DataType = 9
	DataType_Boolean  DataType = 10
	DataType_String   DataType = 11
	DataType_WString  DataType = 12
	DataType_Bytes    DataType = 13
	DataType_Response DataType = 15
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0:  "Int8",
		1:  "Int16",
		2:  "Int32",
		3:  "Int64",
		4:  "UInt8",
		5:  "UInt16",
		6:  "UInt32",
		7:  "UInt64",
		8:  "Float",
		9:  "Double",
		10: "Boolean",
		11: "String",
		12: "WString",
		13: "Bytes",
		15: "Response",
	}
	DataType_value = map[string]int32{
		"Int8":     0,
		"Int16":    1,
		"Int32":    2,
		"Int64":    3,
		"UInt8":    4,
		"UInt16":   5,
		"UInt32":   6,
		"UInt64":   7,
		"Float":    8,
		"Double":   9,
		"Boolean":  10,
		"String":   11,
		"WString":  12,
		"Bytes":    13,
		"Response": 15,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_beeplug_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_beeplug_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{0}
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp uint64            `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp"` // @gotags: yaml:"timestamp"
	Uuid      string            `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty" yaml:"uuid"`            // @gotags: yaml:"uuid"
	Metrics   []*Payload_Metric `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" yaml:"metrics"`      // @gotags: yaml:"metrics"
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeplug_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_beeplug_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Payload) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Payload) GetMetrics() []*Payload_Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type EdgeDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`             // @gotags: yaml:"name"
	Connection string                 `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty" yaml:"connection"` // @gotags: yaml:"connection"
	Variables  []*EdgeDevice_Variable `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" yaml:"variables"`   // @gotags: yaml:"variables"
}

func (x *EdgeDevice) Reset() {
	*x = EdgeDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeplug_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeDevice) ProtoMessage() {}

func (x *EdgeDevice) ProtoReflect() protoreflect.Message {
	mi := &file_beeplug_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeDevice.ProtoReflect.Descriptor instead.
func (*EdgeDevice) Descriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EdgeDevice) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *EdgeDevice) GetVariables() []*EdgeDevice_Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type EntityField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`                                              // @gotags: yaml:"name"
	ControlModule *string                    `protobuf:"bytes,2,opt,name=control_module,json=controlModule,proto3,oneof" json:"control_module,omitempty" yaml:"control_module"` // @gotags: yaml:"control_module"
	Expression    string                     `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty" yaml:"expression"`                                  // @gotags: yaml:"expression"
	IsTransient   bool                       `protobuf:"varint,4,opt,name=is_transient,json=isTransient,proto3" json:"is_transient,omitempty" yaml:"is_transient"`            // @gotags: yaml:"is_transient"
	SetFunctions  []*EntityField_SetFunction `protobuf:"bytes,5,rep,name=set_functions,json=setFunctions,proto3" json:"set_functions,omitempty" yaml:"set_functions"`          // @gotags: yaml:"set_functions"
}

func (x *EntityField) Reset() {
	*x = EntityField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeplug_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityField) ProtoMessage() {}

func (x *EntityField) ProtoReflect() protoreflect.Message {
	mi := &file_beeplug_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityField.ProtoReflect.Descriptor instead.
func (*EntityField) Descriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{2}
}

func (x *EntityField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityField) GetControlModule() string {
	if x != nil && x.ControlModule != nil {
		return *x.ControlModule
	}
	return ""
}

func (x *EntityField) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *EntityField) GetIsTransient() bool {
	if x != nil {
		return x.IsTransient
	}
	return false
}

func (x *EntityField) GetSetFunctions() []*EntityField_SetFunction {
	if x != nil {
		return x.SetFunctions
	}
	return nil
}

type Payload_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty" yaml:"status_code"` // @gotags: yaml:"status_code"
	Body       string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty" yaml:"body"`                                // @gotags: yaml:"body"
	Error      string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty" yaml:"error"`                              // @gotags: yaml:"error"
}

func (x *Payload_Response) Reset() {
	*x = Payload_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeplug_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_Response) ProtoMessage() {}

func (x *Payload_Response) ProtoReflect() protoreflect.Message {
	mi := &file_beeplug_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_Response.ProtoReflect.Descriptor instead.
func (*Payload_Response) Descriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Payload_Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Payload_Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Payload_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Payload_Metric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`                                                // @gotags: yaml:"name"
	DataType  DataType `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=beeplug.DataType" json:"data_type,omitempty" yaml:"data_type"` // @gotags: yaml:"data_type"
	Timestamp uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp"`                                     // @gotags: yaml:"timestamp"
	IsNull    bool     `protobuf:"varint,4,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty" yaml:"is_null"`                             // @gotags: yaml:"is_null"
	Status    string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty" yaml:"status"`                                            // @gotags: yaml:"status"
	// Types that are assignable to Value:
	//
	//	*Payload_Metric_Int32Value
	//	*Payload_Metric_Int64Value
	//	*Payload_Metric_Uint32Value
	//	*Payload_Metric_Uint64Value
	//	*Payload_Metric_FloatValue
	//	*Payload_Metric_DoubleValue
	//	*Payload_Metric_BooleanValue
	//	*Payload_Metric_StringValue
	//	*Payload_Metric_BytesValue
	//	*Payload_Metric_ResponseValue
	Value isPayload_Metric_Value `protobuf_oneof:"value"`
}

func (x *Payload_Metric) Reset() {
	*x = Payload_Metric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeplug_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_Metric) ProtoMessage() {}

func (x *Payload_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_beeplug_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_Metric.ProtoReflect.Descriptor instead.
func (*Payload_Metric) Descriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Payload_Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Payload_Metric) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_Int8
}

func (x *Payload_Metric) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Payload_Metric) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

func (x *Payload_Metric) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (m *Payload_Metric) GetValue() isPayload_Metric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Payload_Metric) GetInt32Value() int32 {
	if x, ok := x.GetValue().(*Payload_Metric_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *Payload_Metric) GetInt64Value() int64 {
	if x, ok := x.GetValue().(*Payload_Metric_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (x *Payload_Metric) GetUint32Value() uint32 {
	if x, ok := x.GetValue().(*Payload_Metric_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (x *Payload_Metric) GetUint64Value() uint64 {
	if x, ok := x.GetValue().(*Payload_Metric_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (x *Payload_Metric) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*Payload_Metric_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *Payload_Metric) GetDoubleValue() float64 {
	if x, ok := x.GetValue().(*Payload_Metric_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *Payload_Metric) GetBooleanValue() bool {
	if x, ok := x.GetValue().(*Payload_Metric_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (x *Payload_Metric) GetStringValue() string {
	if x, ok := x.GetValue().(*Payload_Metric_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Payload_Metric) GetBytesValue() []byte {
	if x, ok := x.GetValue().(*Payload_Metric_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (x *Payload_Metric) GetResponseValue() *Payload_Response {
	if x, ok := x.GetValue().(*Payload_Metric_ResponseValue); ok {
		return x.ResponseValue
	}
	return nil
}

type isPayload_Metric_Value interface {
	isPayload_Metric_Value()
}

type Payload_Metric_Int32Value struct {
	Int32Value int32 `protobuf:"varint,6,opt,name=int32_value,json=int32Value,proto3,oneof" yaml:"int32_value"` // @gotags: yaml:"int32_value"
}

type Payload_Metric_Int64Value struct {
	Int64Value int64 `protobuf:"varint,7,opt,name=int64_value,json=int64Value,proto3,oneof" yaml:"int64_value"` // @gotags: yaml:"int64_value"
}

type Payload_Metric_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,10,opt,name=uint32_value,json=uint32Value,proto3,oneof" yaml:"uint32_value"` // @gotags: yaml:"uint32_value"
}

type Payload_Metric_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,11,opt,name=uint64_value,json=uint64Value,proto3,oneof" yaml:"uint64_value"` // @gotags: yaml:"uint64_value"
}

type Payload_Metric_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,12,opt,name=float_value,json=floatValue,proto3,oneof" yaml:"float_value"` // @gotags: yaml:"float_value"
}

type Payload_Metric_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,13,opt,name=double_value,json=doubleValue,proto3,oneof" yaml:"double_value"` // @gotags: yaml:"double_value"
}

type Payload_Metric_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,14,opt,name=boolean_value,json=booleanValue,proto3,oneof" yaml:"boolean_value"` // @gotags: yaml:"boolean_value"
}

type Payload_Metric_StringValue struct {
	StringValue string `protobuf:"bytes,15,opt,name=string_value,json=stringValue,proto3,oneof" yaml:"string_value"` // @gotags: yaml:"string_value"
}

type Payload_Metric_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,16,opt,name=bytes_value,json=bytesValue,proto3,oneof" yaml:"bytes_value"` // @gotags: yaml:"bytes_value"
}

type Payload_Metric_ResponseValue struct {
	ResponseValue *Payload_Response `protobuf:"bytes,17,opt,name=response_value,json=responseValue,proto3,oneof" yaml:"response_value"` // @gotags: yaml:"response_value"
}

func (*Payload_Metric_Int32Value) isPayload_Metric_Value() {}

func (*Payload_Metric_Int64Value) isPayload_Metric_Value() {}

func (*Payload_Metric_Uint32Value) isPayload_Metric_Value() {}

func (*Payload_Metric_Uint64Value) isPayload_Metric_Value() {}

func (*Payload_Metric_FloatValue) isPayload_Metric_Value() {}

func (*Payload_Metric_DoubleValue) isPayload_Metric_Value() {}

func (*Payload_Metric_BooleanValue) isPayload_Metric_Value() {}

func (*Payload_Metric_StringValue) isPayload_Metric_Value() {}

func (*Payload_Metric_BytesValue) isPayload_Metric_Value() {}

func (*Payload_Metric_ResponseValue) isPayload_Metric_Value() {}

type EdgeDevice_Variable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" yaml:"name"`                                                // @gotags: yaml:"name"
	DataType  DataType `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=beeplug.DataType" json:"data_type,omitempty" yaml:"data_type"` // @gotags: yaml:"data_type"
	Address   string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`                                          // @gotags: yaml:"address"
	Threshold *float64 `protobuf:"fixed64,4,opt,name=threshold,proto3,oneof" json:"threshold,omitempty" yaml:"threshold"`                              // @gotags: yaml:"threshold"
	Length    *uint32  `protobuf:"varint,5,opt,name=length,proto3,oneof" json:"length,omitempty" yaml:"length"`                                     // @gotags: yaml:"length"
}

func (x *EdgeDevice_Variable) Reset() {
	*x = EdgeDevice_Variable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeplug_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EdgeDevice_Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeDevice_Variable) ProtoMessage() {}

func (x *EdgeDevice_Variable) ProtoReflect() protoreflect.Message {
	mi := &file_beeplug_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeDevice_Variable.ProtoReflect.Descriptor instead.
func (*EdgeDevice_Variable) Descriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EdgeDevice_Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EdgeDevice_Variable) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_Int8
}

func (x *EdgeDevice_Variable) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EdgeDevice_Variable) GetThreshold() float64 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *EdgeDevice_Variable) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

type EntityField_SetFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device     string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty" yaml:"device"`         // @gotags: yaml:"device"
	Variable   string `protobuf:"bytes,2,opt,name=variable,proto3" json:"variable,omitempty" yaml:"variable"`     // @gotags: yaml:"variable"
	Expression string `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty" yaml:"expression"` // @gotags: yaml:"expression"
}

func (x *EntityField_SetFunction) Reset() {
	*x = EntityField_SetFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beeplug_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityField_SetFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityField_SetFunction) ProtoMessage() {}

func (x *EntityField_SetFunction) ProtoReflect() protoreflect.Message {
	mi := &file_beeplug_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityField_SetFunction.ProtoReflect.Descriptor instead.
func (*EntityField_SetFunction) Descriptor() ([]byte, []int) {
	return file_beeplug_proto_rawDescGZIP(), []int{2, 0}
}

func (x *EntityField_SetFunction) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *EntityField_SetFunction) GetVariable() string {
	if x != nil {
		return x.Variable
	}
	return ""
}

func (x *EntityField_SetFunction) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

var File_beeplug_proto protoreflect.FileDescriptor

var file_beeplug_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x65, 0x65, 0x70, 0x6c, 0x75, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x62, 0x65, 0x65, 0x70, 0x6c, 0x75, 0x67, 0x22, 0xf7, 0x05, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x65, 0x65, 0x70, 0x6c, 0x75,
	0x67, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x55, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x1a, 0xaf, 0x04, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2e, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x62, 0x65, 0x65, 0x70, 0x6c, 0x75, 0x67, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x73, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x4e, 0x75, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21,
	0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x75, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x48,
	0x00, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21,
	0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a,
	0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x62, 0x65, 0x65, 0x70, 0x6c, 0x75, 0x67, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xc0, 0x02, 0x0a, 0x0a, 0x45, 0x64, 0x67, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x65, 0x65, 0x70, 0x6c,
	0x75, 0x67, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x1a, 0xc1, 0x01, 0x0a, 0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x62, 0x65, 0x65, 0x70, 0x6c, 0x75, 0x67, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x09,
	0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x00, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x12,
	0x1b, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x01, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0xcd, 0x02, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x5f,
	0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x62, 0x65, 0x65, 0x70, 0x6c, 0x75, 0x67, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x73, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x61, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2a, 0xba, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x74, 0x38, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x49, 0x6e, 0x74, 0x31, 0x36, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x10, 0x03, 0x12, 0x09, 0x0a,
	0x05, 0x55, 0x49, 0x6e, 0x74, 0x38, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x6e, 0x74,
	0x31, 0x36, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x10, 0x06,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x10, 0x0a,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x0b, 0x12, 0x0b, 0x0a, 0x07,
	0x57, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x0c, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x10, 0x0d, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x10, 0x0f, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x62, 0x65, 0x65, 0x70, 0x6c, 0x75, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beeplug_proto_rawDescOnce sync.Once
	file_beeplug_proto_rawDescData = file_beeplug_proto_rawDesc
)

func file_beeplug_proto_rawDescGZIP() []byte {
	file_beeplug_proto_rawDescOnce.Do(func() {
		file_beeplug_proto_rawDescData = protoimpl.X.CompressGZIP(file_beeplug_proto_rawDescData)
	})
	return file_beeplug_proto_rawDescData
}

var file_beeplug_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_beeplug_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_beeplug_proto_goTypes = []interface{}{
	(DataType)(0),                   // 0: beeplug.DataType
	(*Payload)(nil),                 // 1: beeplug.Payload
	(*EdgeDevice)(nil),              // 2: beeplug.EdgeDevice
	(*EntityField)(nil),             // 3: beeplug.EntityField
	(*Payload_Response)(nil),        // 4: beeplug.Payload.Response
	(*Payload_Metric)(nil),          // 5: beeplug.Payload.Metric
	(*EdgeDevice_Variable)(nil),     // 6: beeplug.EdgeDevice.Variable
	(*EntityField_SetFunction)(nil), // 7: beeplug.EntityField.SetFunction
}
var file_beeplug_proto_depIdxs = []int32{
	5, // 0: beeplug.Payload.metrics:type_name -> beeplug.Payload.Metric
	6, // 1: beeplug.EdgeDevice.variables:type_name -> beeplug.EdgeDevice.Variable
	7, // 2: beeplug.EntityField.set_functions:type_name -> beeplug.EntityField.SetFunction
	0, // 3: beeplug.Payload.Metric.data_type:type_name -> beeplug.DataType
	4, // 4: beeplug.Payload.Metric.response_value:type_name -> beeplug.Payload.Response
	0, // 5: beeplug.EdgeDevice.Variable.data_type:type_name -> beeplug.DataType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_beeplug_proto_init() }
func file_beeplug_proto_init() {
	if File_beeplug_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beeplug_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beeplug_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beeplug_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beeplug_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beeplug_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload_Metric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beeplug_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EdgeDevice_Variable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beeplug_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityField_SetFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_beeplug_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_beeplug_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Payload_Metric_Int32Value)(nil),
		(*Payload_Metric_Int64Value)(nil),
		(*Payload_Metric_Uint32Value)(nil),
		(*Payload_Metric_Uint64Value)(nil),
		(*Payload_Metric_FloatValue)(nil),
		(*Payload_Metric_DoubleValue)(nil),
		(*Payload_Metric_BooleanValue)(nil),
		(*Payload_Metric_StringValue)(nil),
		(*Payload_Metric_BytesValue)(nil),
		(*Payload_Metric_ResponseValue)(nil),
	}
	file_beeplug_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beeplug_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_beeplug_proto_goTypes,
		DependencyIndexes: file_beeplug_proto_depIdxs,
		EnumInfos:         file_beeplug_proto_enumTypes,
		MessageInfos:      file_beeplug_proto_msgTypes,
	}.Build()
	File_beeplug_proto = out.File
	file_beeplug_proto_rawDesc = nil
	file_beeplug_proto_goTypes = nil
	file_beeplug_proto_depIdxs = nil
}
